[hugoVersion]
extended = true
min = "0.96.0"

[[mounts]]
source = "data"
target = "data"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-hooks"
